const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),file=fs.readFileSync(path.join(root,'README.md'),'utf8').match(/\((game_version[^)]+\.html)\)/)[1];
const hooks=`window.enemyQA={THREE,createZombie,resetGame,renderScene,updateUI,updateWeapon,updateZombies,updateCombatEffects,fireBullet,killZombie,applyLegDamage,startCampaignBoss,zombieTypeConfigs,humanoidVisuals,bloodEffects,get scene(){return scene},get camera(){return camera},get renderer(){return renderer},get zombies(){return zombies},get controls(){return controls},show(){document.body.classList.remove('menu-open');overlay.style.display='none';operationStarted=true;controls.isLocked=false;}};`;
const source=fs.readFileSync(path.join(root,file),'utf8').replace('        init();',hooks+'\n        init();');
const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html; charset=utf-8');res.end(source)});
(async()=>{let browser;try{await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});const p=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));const captures=path.join(root,'docs/captures/zombies-v37');fs.mkdirSync(captures,{recursive:true});for(const quality of ['low','high']){await p.goto(`http://127.0.0.1:${server.address().port}/?quality=${quality}`);await p.waitForFunction(()=>window.gameBootComplete&&window.enemyQA,{timeout:60000});
const mapping=await p.evaluate(()=>{const q=enemyQA,T=q.THREE;q.resetGame();const all={};for(const [key,count]of[['normal',2],['runner',3],['brute',1],['shooter',1],['detonator',1]]){all[key]=[];for(let i=0;i<count;i++){q.createZombie(new T.Vector3(i*3,0,-8),q.zombieTypeConfigs[key]);all[key].push(q.zombies.at(-1).userData.assetId)}}return all});assert.deepEqual(mapping,{normal:['z07','z08'],runner:['z02','z04','z06'],brute:['z05'],shooter:['z03'],detonator:['z03']});
const roles=await p.evaluate(()=>{const q=enemyQA;q.resetGame();q.startCampaignBoss();const boss=q.zombies.find(z=>z.userData.isBoss);const bossCorrect=boss.userData.assetId==='z01'&&boss.userData.typeName==='Guardião';q.resetGame();const colors=[];for(const type of ['shooter','detonator']){q.createZombie(new q.THREE.Vector3(0,0,-5),q.zombieTypeConfigs[type]);let color;q.zombies.at(-1).userData.importedHumanoid.root.traverse(m=>{if(color===undefined&&m.isMesh)color=(Array.isArray(m.material)?m.material[0]:m.material).color.getHex()});colors.push(color);}return{bossCorrect,different:colors[0]!==colors[1]}});assert(roles.bossCorrect&&roles.different,JSON.stringify(roles));
const rows=[];for(const [id,type] of [['z01','normal'],['z02','runner'],['z03','shooter'],['z03','detonator'],['z04','runner'],['z05','brute'],['z06','runner'],['z07','normal'],['z08','normal']]){const r=await p.evaluate(([id,type])=>{const q=enemyQA,T=q.THREE;q.resetGame();q.show();q.createZombie(new T.Vector3(0,0,-4),{...q.zombieTypeConfigs[type],assetId:id});const z=q.zombies[0],m=z.userData.importedHumanoid;const skeletons=[];m.root.traverse(o=>{if(o.isSkinnedMesh)skeletons.push(o.skeleton)});const bones=skeletons.flatMap(s=>s.bones),before=bones.map(b=>b.quaternion.toArray().join(','));q.humanoidVisuals.update(m,.35,z.userData,2);const animated=bones.some((b,i)=>b.quaternion.toArray().join(',')!==before[i]);q.createZombie(new T.Vector3(8,0,-4),{...q.zombieTypeConfigs[type],assetId:id});const other=[];q.zombies[1].userData.importedHumanoid.root.traverse(o=>{if(o.isSkinnedMesh)other.push(o.skeleton)});const independent=skeletons.every(s=>!other.includes(s));q.killZombie(q.zombies[1],{awardScore:false,allowPowerup:false});q.bloodEffects.clear();q.camera.position.set(2.8,2.1,1);q.camera.lookAt(0,1.45,-4);const light=new T.HemisphereLight(0xffffff,0x665555,2);q.scene.add(light);q.scene.updateMatrixWorld(true);const box=new T.Box3().setFromObject(m.root);q.updateUI();q.updateWeapon(.016);q.renderScene();q.scene.remove(light);return{id,animated,independent,size:box.getSize(new T.Vector3()).toArray(),skins:skeletons.length}},[id,type]);rows.push(r);assert(r.animated&&r.independent&&r.skins>0,JSON.stringify(r));assert(r.size.every(x=>Number.isFinite(x)&&x>0&&x<7),JSON.stringify(r));if(quality==='high')await p.screenshot({path:path.join(captures,id+(type==='detonator'?'-detonator':'')+'.png')});}
const blood=await p.evaluate(()=>{const q=enemyQA,T=q.THREE;q.resetGame();q.show();q.createZombie(new T.Vector3(0,0,-4),q.zombieTypeConfigs.normal);q.camera.position.set(0,1.8,0);q.camera.lookAt(0,1.5,-4);q.scene.updateMatrixWorld(true);q.fireBullet(75,42,0,1,false,false);const realHit=q.bloodEffects.active>0;for(let i=0;i<150;i++)q.bloodEffects.spawn(q.scene,new T.Vector3((i%9-4)*.4,1,-3-Math.floor(i/9)*.1),i%5===0);const capped=q.bloodEffects.active===q.bloodEffects.capacity;const before=q.bloodEffects.active;q.controls.isLocked=false;q.updateZombies(2);const paused=q.bloodEffects.active===before;q.camera.position.set(1,3,1);q.camera.lookAt(0,0,-4);q.renderScene();return{realHit,capped,paused}});assert(blood.realHit&&blood.capped&&blood.paused,JSON.stringify(blood));if(quality==='high')await p.screenshot({path:path.join(captures,'blood.png')});
const lifecycle=await p.evaluate(()=>{const q=enemyQA;q.updateCombatEffects(50);const expired=q.bloodEffects.active===0;q.resetGame();const cleared=q.bloodEffects.active===0&&!q.bloodEffects.mesh.parent;const rows=[];for(let i=0;i<4;i++){q.resetGame();for(const type of ['normal','runner','brute','shooter','detonator'])q.createZombie(new q.THREE.Vector3(0,0,-5),q.zombieTypeConfigs[type]);q.renderScene();q.resetGame();q.renderScene();rows.push({...q.renderer.info.memory})}return{expired,cleared,rows}});assert(lifecycle.expired&&lifecycle.cleared);assert(lifecycle.rows.every(r=>r.geometries===lifecycle.rows[0].geometries&&r.textures===lifecycle.rows[0].textures),JSON.stringify(lifecycle));assert.deepEqual(errors,[]);console.log(JSON.stringify({quality,mapping,roles,models:rows,blood,lifecycle}));}}finally{await browser?.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
