const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),file=fs.readFileSync(path.join(root,'README.md'),'utf8').match(/\((game_version[^)]+\.html)\)/)[1];
const hooks=`window.v41QA={THREE,resetGame,applyDamage,startWave,updateUI,updateWaveHud,updateContainmentHud,updateTracers,createTracer,createAmmoPickup,renderScene,openJournal,closeJournal,killZombie,createZombie,gameEvents,journal,generatorNetwork,campaign,waveDirector,generators,campaignNodes,get health(){return health},get score(){return score},get gameOver(){return gameOver},get operationStarted(){return operationStarted},get scene(){return scene},get camera(){return camera},get renderer(){return renderer},get zombies(){return zombies},get controls(){return controls},get tracers(){return tracers},show(){operationStarted=true;document.body.classList.remove('menu-open');overlay.style.display='none';controls.isLocked=true;}};`;
const source=fs.readFileSync(path.join(root,file),'utf8').replace('        init();',hooks+'\n        init();');
const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html;charset=utf-8');res.end(source)});
(async()=>{let browser;try{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
 const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const dir=path.join(root,'docs/captures/v41');fs.mkdirSync(dir,{recursive:true});
 for(const quality of ['low','high']){
  await page.goto(`http://127.0.0.1:${server.address().port}/?quality=${quality}`);await page.waitForFunction(()=>window.gameBootComplete&&window.v41QA,{timeout:90000});
  const challenge=await page.evaluate(()=>{const q=v41QA,T=q.THREE;q.resetGame();q.show();const auto=q.journal.contract.status==='active';q.gameEvents.emit('waveCompleted',{wave:1});q.waveDirector.phase='intermission';q.updateWaveHud();const next=q.journal.contract.wave===2&&q.journal.contract.status==='upcoming'&&!document.getElementById('challenge-preview').hidden;q.gameEvents.emit('enemyKilled',{wave:1,enemyId:900,cause:'melee',reward:125});const notEarly=q.journal.contract.progress===0;q.startWave(2);const activated=q.journal.contract.status==='active';for(let i=0;i<3;i++)q.gameEvents.emit('enemyKilled',{wave:2,enemyId:901+i,cause:'melee',reward:125});return{auto,next,notEarly,activated,reward:q.journal.completed===1};});
  Object.entries(challenge).forEach(([k,v])=>assert(v,k));
  await page.evaluate(()=>{const q=v41QA;q.gameEvents.emit('waveCompleted',{wave:2});q.waveDirector.phase='intermission';q.waveDirector.remaining=10;q.controls.isLocked=false;q.updateWaveHud();q.renderScene();});await page.screenshot({path:path.join(dir,`challenge-${quality}.png`)});
  const generator=await page.evaluate(()=>{const q=v41QA;q.resetGame();q.show();const g=q.generators[0];q.generatorNetwork.start(0,1);q.generatorNetwork.active.elapsed=14;q.camera.position.copy(g.position).add(new q.THREE.Vector3(0,1.8,6));q.camera.lookAt(g.position.clone().add(new q.THREE.Vector3(0,1,0)));q.controls.isLocked=false;q.updateContainmentHud();q.renderScene();const rect=document.getElementById('generator-hud').getBoundingClientRect();return{center:Math.abs(rect.x+rect.width/2-innerWidth/2)<2,top:rect.y<50,visible:!document.getElementById('generator-hud').hidden,large:g.scale.x===1.2,label:!!g.getObjectByName('physical-label'),papers:q.campaignNodes.filter(n=>n.userData.role==='record').every(n=>n.getObjectByName('scattered-record-'+n.userData.id)?.children.length===5)};});Object.entries(generator).forEach(([k,v])=>assert(v,k));await page.screenshot({path:path.join(dir,`generator-${quality}.png`)});
  await page.evaluate(()=>{const q=v41QA;q.resetGame();q.show();q.controls.isLocked=false;q.camera.position.set(5.6,1.8,59);q.camera.lookAt(7,.65,55);q.createAmmoPickup(new q.THREE.Vector3(6,0,56.2));q.updateUI();q.renderScene();});await page.screenshot({path:path.join(dir,`signage-${quality}.png`)});
  const effects=await page.evaluate(()=>{const q=v41QA,T=q.THREE;q.resetGame();q.show();const lights=()=>{let n=0;q.scene.traverse(o=>{if(o.isPointLight)n++});return n};const before=lights();let verticesBefore=q.renderer.info.memory.geometries;for(let i=0;i<100;i++){q.createTracer(new T.Vector3(0,1.8,-1),new T.Vector3(0,1,-5));q.updateTracers(.15)}q.renderScene();const after=lights();q.updateTracers(1);q.resetGame();let empty=0;q.scene.traverse(o=>{if(o.userData.legacyLabel&&o.children.length)empty++});return{stableLights:before===after,bounded:q.renderer.info.memory.geometries<=verticesBefore+4,reset:q.tracers.length===0,noFloatingText:empty===0};});Object.entries(effects).forEach(([k,v])=>assert(v,k));
  await page.evaluate(()=>{const q=v41QA;q.generatorNetwork.completed.add(0);q.gameEvents.emit('generatorCompleted',{generator:0});q.updateUI();q.openJournal();});assert.equal(await page.locator('#field-journal .journal-page').count(),2);assert.equal(await page.getByRole('button',{name:/ACEITAR/}).count(),0);await page.screenshot({path:path.join(dir,`journal-${quality}.png`)});
  await page.setViewportSize({width:640,height:360});await page.screenshot({path:path.join(dir,`journal-compact-${quality}.png`)});assert(await page.locator('#close-journal').isVisible());await page.keyboard.press('Escape');assert.equal(await page.locator('#field-journal').count(),0);await page.setViewportSize({width:1440,height:900});await page.evaluate(()=>{const q=v41QA;q.resetGame();q.show();q.applyDamage(999,'test','Teste');q.controls.isLocked=false;q.controls.dispatchEvent({type:'unlock'});});
  assert(await page.getByRole('button',{name:'VOLTAR AO MENU INICIAL',exact:true}).isVisible());await page.screenshot({path:path.join(dir,`game-over-${quality}.png`)});
  await page.getByRole('button',{name:'VOLTAR AO MENU INICIAL',exact:true}).click();assert(await page.getByRole('button',{name:'JOGAR',exact:true}).isVisible());assert(await page.evaluate(()=>!v41QA.gameOver&&!v41QA.operationStarted&&!v41QA.controls.isLocked&&v41QA.health===100&&v41QA.score===0));
  await page.getByRole('button',{name:'JOGAR',exact:true}).click();await page.waitForFunction(()=>v41QA.controls.isLocked);await page.evaluate(()=>{v41QA.controls.isLocked=false;v41QA.updateUI();v41QA.renderScene();});
  const hud=await page.locator('#ui').boundingBox();assert(hud.x<40&&hud.y<40);await page.screenshot({path:path.join(dir,`hud-top-left-${quality}.png`)});
  await page.setViewportSize({width:640,height:360});const compact=await page.locator('#ui').boundingBox();assert(compact.x<25&&compact.y<25);await page.setViewportSize({width:1440,height:900});
  assert.deepEqual(errors,[]);console.log(JSON.stringify({quality,challenge,generator,effects,gameOverMenu:true,hudTopLeft:true}));
 }
 }finally{await browser?.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
