// Keep a single rules source while distributing an HTML that supports file://.
import {readFileSync,writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=fileURLToPath(new URL('../',import.meta.url));
const name=readFileSync(path.join(root,'README.md'),'utf8').match(/\((game_version[^)]+\.html)\)/)[1];
const file=path.join(root,name),html=readFileSync(file,'utf8');
const rules=readFileSync(path.join(root,'game-systems.mjs'),'utf8').replace(/\r\n/g,'\n').replace(/^export /gm,'');
if(/<\/script/i.test(rules))throw new Error('Rules cannot contain a closing script tag');
const marker=/\/\/ BEGIN EMBEDDED RULES[\s\S]*?\/\/ END EMBEDDED RULES/;
if(!marker.test(html))throw new Error('Missing embedded rules markers');
let generated=html.replace(marker,()=>`// BEGIN EMBEDDED RULES — generated by scripts/build-game.mjs\n${rules.trim()}\n// END EMBEDDED RULES`);
const telemetry=readFileSync(path.join(root,'telemetry.mjs'),'utf8').replace(/\r\n/g,'\n').replace(/^export /gm,'');
if(/<\/script/i.test(telemetry))throw new Error('Telemetry cannot contain a closing script tag');
const telemetryMarker=/\/\/ BEGIN EMBEDDED TELEMETRY[\s\S]*?\/\/ END EMBEDDED TELEMETRY/;
if(!telemetryMarker.test(generated))throw new Error('Missing telemetry markers');
generated=generated.replace(telemetryMarker,()=>`// BEGIN EMBEDDED TELEMETRY — generated by scripts/build-game.mjs\n${telemetry.trim()}\n// END EMBEDDED TELEMETRY`);
if(process.argv.includes('--check')){
    if(generated.replace(/\r\n/g,'\n')!==html.replace(/\r\n/g,'\n'))throw new Error('Stale embedded rules: run node scripts/build-game.mjs');
    console.log('Embedded rules match game-systems.mjs');
}else{writeFileSync(file,generated);console.log(`Updated ${name}`);}
