// Keep a single rules source while distributing an HTML that supports file://.
import {readFileSync,writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=fileURLToPath(new URL('../',import.meta.url));
const name=readFileSync(path.join(root,'README.md'),'utf8').match(/\((game_version[^)]+\.html)\)/)[1];
const file=path.join(root,name),html=readFileSync(file,'utf8');
const rules=readFileSync(path.join(root,'game-systems.mjs'),'utf8').replace(/\r\n/g,'\n').replace(/^export /gm,'');
if(/<\/script/i.test(rules))throw new Error('Rules cannot contain a closing script tag');
const marker=/\/\/ BEGIN EMBEDDED RULES[\s\S]*?\/\/ END EMBEDDED RULES/;
if(!marker.test(html))throw new Error('Missing embedded rules markers');
let generated=html.replace(marker,()=>`// BEGIN EMBEDDED RULES — generated by scripts/build-game.mjs\n${rules.trim()}\n// END EMBEDDED RULES`);
const telemetry=readFileSync(path.join(root,'telemetry.mjs'),'utf8').replace(/\r\n/g,'\n').replace(/^export /gm,'');
if(/<\/script/i.test(telemetry))throw new Error('Telemetry cannot contain a closing script tag');
const telemetryMarker=/\/\/ BEGIN EMBEDDED TELEMETRY[\s\S]*?\/\/ END EMBEDDED TELEMETRY/;
if(!telemetryMarker.test(generated))throw new Error('Missing telemetry markers');
generated=generated.replace(telemetryMarker,()=>`// BEGIN EMBEDDED TELEMETRY — generated by scripts/build-game.mjs\n${telemetry.trim()}\n// END EMBEDDED TELEMETRY`);
// Binary sources stay in assets; the released document remains standalone for file://.
const weaponMarker=/\/\/ BEGIN EMBEDDED WEAPON ASSETS[^\n]*\n[\s\S]*?\/\/ END EMBEDDED WEAPON ASSETS/;
if(weaponMarker.test(generated)){
    const weapons={};
    for(const [id,asset] of [['pistol','beretta'],['smg','thompson'],['assault_rifle','ak47']])
        weapons[id]=readFileSync(path.join(root,'assets/weapons',asset+'.glb')).toString('base64');
    generated=generated.replace(weaponMarker,()=>`// BEGIN EMBEDDED WEAPON ASSETS — generated by scripts/build-game.mjs\n        const EMBEDDED_WEAPON_ASSETS = ${JSON.stringify(weapons)};\n        // END EMBEDDED WEAPON ASSETS`);
}
const worldMarker=/\/\/ BEGIN EMBEDDED WORLD ASSETS[^\n]*\n[\s\S]*?\/\/ END EMBEDDED WORLD ASSETS/;
if(worldMarker.test(generated)){
    const assets={};
    for(const [id,file] of [['dog1','enemies/d01.glb'],['dog2','enemies/d02.glb'],['crate','props/mystery-box.glb']])
        assets[id]=readFileSync(path.join(root,'assets',file)).toString('base64');
    generated=generated.replace(worldMarker,()=>`// BEGIN EMBEDDED WORLD ASSETS — generated by scripts/build-game.mjs\n        const EMBEDDED_WORLD_ASSETS = ${JSON.stringify(assets)};\n        // END EMBEDDED WORLD ASSETS`);
}
if(process.argv.includes('--check')){
    if(generated.replace(/\r\n/g,'\n')!==html.replace(/\r\n/g,'\n'))throw new Error('Stale embedded rules: run node scripts/build-game.mjs');
    console.log('Embedded rules match game-systems.mjs');
}else{writeFileSync(file,generated);console.log(`Updated ${name}`);}
